# assignment 1

In [2]:
import numpy as np


### 1(A) Calculate the sum, mean, median, and standard deviation of the elements in the array.  

In [4]:
list1 =list(range(1,21))
arr = np.array(list1)

arr_sum = int(sum(arr))
arr_mean = float(np.mean(arr))
arr_median = float(np.median(arr))
arr_std = float(np.std(arr))
print(arr)
print(f"Sum = {arr_sum}")
print(f"Mean = {arr_mean}")
print(f"Median = {arr_median}")
print(f"standard deviation = {arr_std}")

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Sum = 210
Mean = 10.5
Median = 10.5
standard deviation = 5.766281297335398


### 1(B)  b. Find the indices of elements greater than 10 in the array.  

In [36]:
idx = np.where(arr > 10)[0]
print(f" arr indices of elements greater than 10 :{idx} ")

 arr indices of elements greater than 10 :[10 11 12 13 14 15 16 17 18 19] 


## 2. Create a 2D NumPy array of shape 4 X 4 with numbers ranging from 1 to 16. ##2(A) Print the array.
### 2(A) Print the array. 

In [6]:
arr_2d = np.arange(1,17).reshape(4,4)
print(f" 1 to 16 4X4 arr ={arr_2d}")

 1 to 16 4X4 arr =[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


### 2(B)Find the transpose of the array.  

In [48]:
print(f"transpose of the array:{arr_2d.T}")

transpose of the array:[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


### 2(C) Calculate the row-wise and column-wise sums of the array.  

In [51]:
print(f"row-wise Sum={np.sum(arr_2d,axis=1)}")
print(f"column-wise Sum={np.sum(arr_2d,axis=0)}")

row-wise Sum=[10 26 42 58]
column-wise Sum=[28 32 36 40]


## 3. Create two 3 X 3 arrays filled with random integers between 1 and 20.  
### 3(A) Perform element-wise addition, subtraction, and multiplication.  

In [7]:
arr3 =np.arange(1,10).reshape(3,3)
arr4 =np.arange(11,20).reshape(3,3)
print(arr3)
print(arr4)

print(f"addition={arr3+arr4}")
print(f"subtraction={arr3-arr4}")
print(f"multiplication={arr3*arr4}")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
addition=[[12 14 16]
 [18 20 22]
 [24 26 28]]
subtraction=[[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]
multiplication=[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]


### 3(B) Compute the dot product of the two arrays.  

In [67]:
print(f"dot product of the two arrays={np.dot(arr3, arr4)}")

dot product of the two arrays=[[ 90  96 102]
 [216 231 246]
 [342 366 390]]


## 4. Reshape a 1D array of size 12 into a 3 X 4 2D array and slice the first two rows and last two columns.  

In [68]:
arr1 =np.arange(1,13)

In [69]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [70]:
res = arr1.reshape(3,4)

In [74]:
print(f" Reshape a 1D array of size 12 into a 3 X 4 :{res}")

 Reshape a 1D array of size 12 into a 3 X 4 :[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [76]:
print(f"slice the first two rows and last two columns is:{res[:2,-2:]} " )

slice the first two rows and last two columns is:[[3 4]
 [7 8]] 
